name: CMake MacOS GCC

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-10.15, macos-11 ]
        compiler: [ 9, 10, 11 ]

    name: ${{ matrix.platform }} - GCC ${{ matrix.compiler }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        env:
          CC: gcc-${{ matrix.compiler }}
          CXX: g++-${{ matrix.compiler }}
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ github.workspace }}/build/test
        run: ctest -C ${{ env.BUILD_TYPE }} --rerun-failed --output-on-failure
